### ISSUE TITLE
Windows Script

### ISSUE THREAD

**Issue by securitypimp** [agiallombardo/TA-netneighbor#1]
I noticed in the deployment section of the readme it says "Deploy to universal forwarder and enable the script relevant to the operating system."  Do you plan on adding a Windows script?

**Comment by agiallombardo** [comment]
Sorry for the extremely late reply.

Yes, I will be at some point. Windows doesn't display broadcast addresses so additional calculations will be required.

**Comment by agiallombardo** [comment]
Completed
